name: Sync to Gitee
on:
  push:
    branches:
      - main  # 或者 master
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/winetx-winetx/openclaw
          dst: gitee/winetx/openclaw
          dst_key: ${{ secrets.GITEE_PASSWORD }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          static_list: "openclaw"
