name: Sync to Gitee
on:
  push:
    branches:
      - main  # 或者 master
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/gitee-sync@v0.1
        with:
          src: https://github.com/winetx-winetx/openclaw.git
          dst: https://gitee.com/winetx/openclaw.git
          dst_key: ${{ secrets.GITEE_PASSWORD }}
          dst_token: ${{ secrets.GITEE_PASSWORD }}
          static_list: "openclaw"
